export const TEXT_PROTOCOL_TOOL_LIST_TAG = 'tool_list';
export const TEXT_PROTOCOL_TOOL_TAG = 'tool';
export const TEXT_PROTOCOL_TOOL_CALL_TAG = 'tool_call';
export const TEXT_PROTOCOL_TOOL_RESULT_TAG = 'tool_result';

export const TEXT_PROTOCOL_TOOL_LIST_OPEN = `<${TEXT_PROTOCOL_TOOL_LIST_TAG}>`;
export const TEXT_PROTOCOL_TOOL_LIST_CLOSE = `</${TEXT_PROTOCOL_TOOL_LIST_TAG}>`;
export const TEXT_PROTOCOL_TOOL_CALL_CLOSE = `</${TEXT_PROTOCOL_TOOL_CALL_TAG}>`;
export const TEXT_PROTOCOL_TOOL_RESULT_OPEN_PREFIX = `<${TEXT_PROTOCOL_TOOL_RESULT_TAG}`;
export const TEXT_PROTOCOL_TOOL_RESULT_CLOSE = `</${TEXT_PROTOCOL_TOOL_RESULT_TAG}>`;

export const TEXT_PROTOCOL_DIAGNOSTIC_EXCERPT_LIMIT = 240;
